services:
  telegram-bot:
    image: dockerhub_repository/telegram-bot:latest
    container_name: telegram-bot
    restart: always
    env_file:
      - .env-file
    networks:
      - infrastructure_app-network

    ports:
      - "8443:8443"
    volumes:
      - /etc/letsencrypt/live/domain.ddns.net:/etc/letsencrypt/live/domain.ddns.net:ro

networks:
   infrastructure_app-network:
     external: true
