spring:
   application:
      name: social-network-bot

   jpa:
      generate-ddl: false
      open-in-view: false
   datasource:
      url: jdbc:postgresql://postgres:5432/bot_db?currentSchema=schema_bot
      username: postgre_user
      password: postgre_secret_password
      driver-class-name: org.postgresql.Driver
      hikari:
         connection-timeout: 10000

   liquibase:
      change-log: classpath:/db/changelog/db.changelog-master.yml

eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}
         #defaultZone: ${EUREKA_URI:http://91.197.98.213:8761/eureka}
         #defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      enabled: true
   instance:
      preferIpAddress: true


telegram:
   bot-token: "${TELEGRAM_BOT_TOKEN}"
   bot-username: "${TELEGRAM_BOT_USERNAME}"
   webhook-url: "${TELEGRAM_WEBHOOK_URL}"
   api-url: "${TELEGRAM_API_URL}"

server:
   port: 8443
   ssl:
      enabled: "${SSL_ENABLED}"
      key-store: "${SSL_KEY_STORE}"
      key-store-password: "${SSL_KEY_STORE_PASSWORD}"
      key-store-type: "${SSL_KEY_STORE_TYPE}"

gateway:
   api:
      url: ${GATEWAY_URL:http://91.197.98.213:8080}